title = "Lewis Tian"
author = "Lewis Tian"
profilePicture = "images/profile.JPG"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 

hidesidebar = true
mainSections = ["post"]
images = ["images/site-feature-image.jpg"]
doNotLoadAnimations = false
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
readMore = true
postSectionName = "blog"
relatedPosts = true
numberOfRelatedPosts = 3

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/lewistian/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Lewis727/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:zt89@cornell.edu"

[mermaid]
# enable = true